name: Run Repo

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run_code:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-22.04]
        cibw_archs: ["auto64"]
        cibw_build: ["cp310", "cp311", "cp312", "cp313"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          miniconda-version: "latest"
          python-version: "3.10"
          channels: conda-forge
          auto-activate-base: false

      - name: Install Conda Dependencies
        run: |
          conda install -y wget


      - name: Run Code
        working-directory: ${{ github.workspace }}
        run: python main.py
